---
title: "GBM detection"
output: html_notebook
---


```{r library load}
library(jsonlite)
library(mlbench)
library(corrplot)
```




```{r}
dataset <- fromJSON(txt = "GBM.json")
dataset <- dataset[, -which(names(dataset) == 'specimens', arr.ind = TRUE)]
dataset <- dataset[, -which(names(dataset) == 'updated', arr.ind = TRUE)]
dataset <- dataset[, -which(names(dataset) == 'inserted', arr.ind = TRUE)]

dataset <- dataset[,order(colnames(dataset))]
```


## EDA

```{r EDA var type}
print("Dataset size")
dim(dataset)
print("Dataset variable names")
names(dataset)

print("Variable classes")
sapply(dataset, class)
dataset$case_id <- as.factor(dataset$case_id)
dataset$gender <- as.factor(dataset$gender)
dataset$ethnicity <- as.factor(dataset$ethnicity)
dataset$race <- as.factor(dataset$race)
dataset$vital_status_at_12months_follow_up <- as.factor(dataset$vital_status_at_12months_follow_up)
dataset$vital_status_at_24months_follow_up <- as.factor(dataset$vital_status_at_24months_follow_up)
dataset$vital_status_at_36months_follow_up <- as.factor(dataset$vital_status_at_36months_follow_up)
dataset$vital_status_at_48months_follow_up <- as.factor(dataset$vital_status_at_48months_follow_up)
dataset$tumor_status_at_12months_follow_up <- as.factor(dataset$tumor_status_at_12months_follow_up)
dataset$tumor_status_at_24months_follow_up <- as.factor(dataset$tumor_status_at_24months_follow_up)
dataset$tumor_status_at_36months_follow_up <- as.factor(dataset$tumor_status_at_36months_follow_up)
dataset$tumor_status_at_48months_follow_up <- as.factor(dataset$tumor_status_at_48months_follow_up)
dataset$tobacco_smoking_history <- as.factor(dataset$tobacco_smoking_history)
dataset$tumor_code <- as.factor(dataset$tumor_code)
dataset$tumor_site <- as.factor(dataset$tumor_site)
dataset$tumor_site_other <- as.factor(dataset$tumor_site_other)
dataset$cause_of_death_at_12months_follow_up <- as.factor(dataset$cause_of_death_at_12months_follow_up)
dataset$cause_of_death_at_24months_follow_up <- as.factor(dataset$cause_of_death_at_24months_follow_up)
dataset$cause_of_death_at_36months_follow_up <- as.factor(dataset$cause_of_death_at_36months_follow_up)
dataset$cause_of_death_at_48months_follow_up <- as.factor(dataset$cause_of_death_at_48months_follow_up)
dataset$discovery_study <- as.factor(dataset$discovery_study)
dataset$`discovery_study/analyzed_samples` <- as.factor(dataset$`discovery_study/analyzed_samples`)

dataset$days_from_initial_diagnosis_to_last_contact_at_12months_follow_up <- as.integer(dataset$days_from_initial_diagnosis_to_last_contact_at_12months_follow_up)
dataset$days_from_initial_pathologic_diagnosis_to_death_at_12months_follow_up <- as.integer(dataset$days_from_initial_pathologic_diagnosis_to_death_at_12months_follow_up)

dataset <- dataset[, -which(names(dataset) == 'histologic_type', arr.ind = TRUE)]
dataset <- dataset[, -which(names(dataset) == 'histologic_type_other', arr.ind = TRUE)]

case_id_with_images <- c("C3L-00016", "C3L-00019", "C3L-00265", "C3L-00278", "C3L-00349", "C3L-00424", "C3L-00506",
                         "C3L-00528", "C3L-00591", "C3L-00631", "C3L-00671", "C3L-00677", "C3L-01040", "C3L-01043",
                         "C3L-01045", "C3L-01046", "C3L-01049", "C3L-01142", "C3L-01146", "C3L-01155", "C3L-01156",
                         "C3L-01327", "C3L-02041", "C3L-02465", "C3L-02504", "C3L-02704", "C3L-02705", "C3L-02706",
                         "C3L-02708", "C3L-03260", "C3L-03266", "C3L-03727", "C3L-03744", "C3L-03747", "C3L-03748",
                         "C3L-04084", "C3N-00661", "C3N-00662", "C3N-00663", "C3N-00665", "C3N-01192", "C3N-01196",
                         "C3N-01505", "C3N-01849", "C3N-01851", "C3N-01852", "C3N-02255", "C3N-02256", "C3N-02286",
                         "C3N-03001", "C3N-03003", "C3N-03755", "C3N-03756", "C3N-04686")

case_id_with_images_index <- c()
for(i in 1:length(case_id_with_images)){
  case_id_with_images_index[i] <-  which(dataset$case_id == case_id_with_images[i], arr.ind = TRUE)
}

dataset_images <- dataset[case_id_with_images_index,]

print("Summary of dataset after changes")
summary(dataset_images)

print("Dataset size")
dim(dataset)
```


```{r EDA plots}
corr <- cor(dataset_images[,1:4])
corrplot(corr, method="circle")
missmap(dataset_images, col=c("black", "grey"), legend=FALSE)

```


## PREPROCESSING



## MODEL BUILDING